name: print_pixel
description: "convert centimeters to pixels at 300 dpi."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  macos_ui: ^2.0.9
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
